### ISSUE TITLE
Error while installing FiPy 0.10.0 with Poetry 1.4.2

### ISSUE THREAD

**Issue by vcutrona** [c0c0n3/kitt4sme.fipy#17]
Hi @c0c0n3 
I got the following error while trying to install FiPy 0.10.0 using Poetry 1.4.2 (latest).

`Failed to clone https://github.com/marrow/uri.git at '5b58db8', verify ref exists on remote.`

I can reproduce the issue in a Docker env, trying to install directly `uri` from source (rev='5b58db8'):
```dockerfile
FROM python:3.8
RUN pip install poetry==1.4.2
RUN poetry new test
WORKDIR test
RUN poetry add git+https://github.com/marrow/uri.git#5b58db8
```

The bug should affect Poetry 1.2+, as discussed in [issue#6455](https://github.com/python-poetry/poetry/issues/6455).
Using the full commit hash solves the issue:

```dockerfile
FROM python:3.8
RUN pip install poetry==1.4.2
RUN poetry new test
WORKDIR test
RUN poetry add git+https://github.com/marrow/uri.git#5b58db87451ca4680004a8993a56bfc4dafff4d4
```

**Comment by c0c0n3** [comment]
@vcutrona thanks so much for reporting this and suggesting a fix. I've fixed the URI deps by using a full commit hash as you suggested and released FiPy `0.11.0` with the fixed URI dependency

- https://github.com/c0c0n3/kitt4sme.fipy/releases/tag/0.11.0
